"""Merge our model card with the platform-generated one already on HF.

Adaption's "Export to HuggingFace" writes a README containing the
AutoScientist config and training-metric images. Overwriting it loses
those. This fetches the existing README, strips its YAML frontmatter, and
writes:

    <our frontmatter>
    <our card>
    ---
    ## Platform training report
    <their card, minus frontmatter>

Usage:
    python pipeline/09_merge_card.py --repo vinod-anbalagan/prism \\
        --card MODEL_CARD_V2.md --dry-run
    python pipeline/09_merge_card.py --repo vinod-anbalagan/prism \\
        --card MODEL_CARD_V2.md
"""

from __future__ import annotations
import argparse
import re
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

APPENDIX_MARKER = "## Platform training report"

APPENDIX_HEADER = f"""
---

{APPENDIX_MARKER}

Generated by Adaption AutoScientist at export time — training
configuration, win-rate chart and loss curves.
"""


def strip_frontmatter(text: str) -> str:
    """Remove a leading --- ... --- YAML block, if present."""
    m = re.match(r"^---\s*\n.*?\n---\s*\n", text, re.DOTALL)
    return text[m.end():] if m else text


def extract_platform_section(text: str) -> str:
    """Recover only Adaption's own content from a possibly-merged README.

    Re-running this script would otherwise append the previous merge —
    our card included — producing a duplicated document. The platform
    section is whatever follows the LAST appendix marker; if the marker
    is absent the README has not been merged yet and is all platform
    content.
    """
    idx = text.rfind(APPENDIX_MARKER)
    if idx == -1:
        return text.strip()
    tail = text[idx + len(APPENDIX_MARKER):]
    # drop our boilerplate sentence that follows the marker
    tail = re.sub(
        r"^\s*Generated by Adaption AutoScientist at export time[^\n]*\n"
        r"(?:configuration[^\n]*\n)?",
        "", tail,
    )
    return tail.strip()


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True, help="e.g. vinod-anbalagan/prism")
    ap.add_argument("--card", default="MODEL_CARD_V2.md",
                    help="our card, relative to repo root")
    ap.add_argument("--repo-type", default="model",
                    choices=["model", "dataset"])
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    ours_path = REPO / args.card
    if not ours_path.is_file():
        sys.exit(f"missing {ours_path}")
    ours = ours_path.read_text().rstrip()

    from huggingface_hub import hf_hub_download, HfApi
    try:
        p = hf_hub_download(args.repo, "README.md", repo_type=args.repo_type,
                            force_download=True)
        raw = strip_frontmatter(Path(p).read_text())
        theirs = extract_platform_section(raw)
        note = " (recovered from a previous merge)" if len(theirs) < len(raw.strip()) else ""
        print(f"fetched existing README: {len(raw)} chars -> "
              f"platform section {len(theirs)} chars{note}")
    except Exception as e:
        print(f"no existing README ({type(e).__name__}); writing ours alone")
        theirs = ""

    merged = ours
    if theirs:
        merged += "\n" + APPENDIX_HEADER + "\n" + theirs + "\n"

    print(f"merged card: {len(merged)} chars, {merged.count(chr(10))} lines")

    if args.dry_run:
        out = Path(tempfile.gettempdir()) / "merged_card.md"
        out.write_text(merged)
        print(f"dry-run — wrote preview to {out}")
        return

    HfApi().upload_file(
        path_or_fileobj=merged.encode(),
        path_in_repo="README.md",
        repo_id=args.repo,
        repo_type=args.repo_type,
        commit_message="add card above platform report",
    )
    prefix = "datasets/" if args.repo_type == "dataset" else ""
    print(f"pushed -> https://huggingface.co/{prefix}{args.repo}")


if __name__ == "__main__":
    main()
